BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb "
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend "
BBFILES += "${LAYERDIR}/recipes-*/*.bb "
BBFILES += "${LAYERDIR}/recipes-*/*.bbappend "

BBFILE_COLLECTIONS += "opendash"
BBFILE_PATTERN_opendash = "^${LAYERDIR}/"
BBFILE_PRIORITY_opendash = "6"


LICENSE_FLAGS_ACCEPTED += "commercial"

#DISTRO_FEATURES:append = " bluetooth"
DISTRO_FEATURES:append = " opengl"
DISTRO_FEATURES:append = " x11"
#DISTRO_FEATURES:append = " x11-base"
#DISTRO_FEATURES:append = " x11-sato"
DISTRO_FEATURES:remove = "wayland"

IMAGE_INSTALL:append = " kernel-modules"

PACKAGECONFIG:append:pn-qtconnectivity = " bluez"
PACKAGECONFIG:append:pn-qtbase = " xcb"
PACKAGECONFIG:append:pn-qtbase = " xcb gles2"
PACKAGECONFIG:append:pn-mesa = " gallium vc4 v3d gbm egl dri3"

MACHINE_FEATURES +=" vc4graphics"
CONFIG_DRM="y"
CONFIG_DRM_VC4="y"
CONFIG_DRM_V3D="y"
CONFIG_DRM_KMS_HELPER="y"
CONFIG_DRM_RENDER="y"
GPU_MEM = "128"
VC4GRAPHICS = "1"

LAYERSERIES_COMPAT_opendash = "walnascar"

