require recipes-core/images/core-image-minimal.bb

IMAGE_INSTALL:append = " libstdc++" 
#IMAGE_INSTALL:append = " openssh openssl openssh-sftp-server"
#IMAGE_INSTALL:append = " raspi-gpio"
#IMAGE_INSTALL += "kernel-module-spidev kernel-module-spi-bcm2835"
#IMAGE_INSTALL:append = " rpi-gpio"
#IMAGE_INSTALL += "bluez5"

IMAGE_INSTALL:append = " dash"
IMAGE_INSTALL:append = " xserver-xorg"
IMAGE_INSTALL:append = " xinit"
IMAGE_INSTALL:append = " xf86-video-modesetting"
IMAGE_INSTALL:append = " xauth"
IMAGE_INSTALL:append = " mesa"
IMAGE_INSTALL:append = " libgl-mesa"
IMAGE_INSTALL:append = " libegl-mesa"
IMAGE_INSTALL:append = " libdrm"
IMAGE_INSTALL:append = " libegl"
IMAGE_INSTALL:append = " xf86-input-libinput"
IMAGE_INSTALL:append = " xserver-xorg-extension-glx"
IMAGE_INSTALL:append = " dropbear"
IMAGE_INSTALL:append = " xterm"
IMAGE_INSTALL:append = " openbox"
IMAGE_INSTALL:append = " kernel-modules"
IMAGE_INSTALL:append = " eudev"
IMAGE_INSTALL:append = " glibc-localedata-en-us"
IMAGE_INSTALL:append = " libinput"
IMAGE_INSTALL:append = " xinput"
IMAGE_INSTALL:append = " pi-bluetooth"
IMAGE_INSTALL:append = " bluez5"
IMAGE_INSTALL:append = " pulseaudio-server"
IMAGE_INSTALL:append = " pulseaudio-module-dbus-protocol"